Feature/title
wolox-training/ch-react pull request #2
Opened 2018-05-30 13:13 UTC by CarlosHWolox

## Summary
Added html/css code for titles with image 

## Screenshot
![titles](https://user-images.githubusercontent.com/39716909/40722135-16f003ee-63e1-11e8-9f03-3938be76bd70.png)

## Trello Card
https://trello.com/c/qvurUwqM/21-page-titles

2018-05-30 16:45 UTC, HarryPerez requested changes
Very good! please check all those comments i have written in order order to fix a few things

2018-05-30 16:45 UTC, HarryPerez commented on index.html
> +        <img width="50px" height="50px" src="./assets/triangle.svg" alt="triangle">
If you look at the card image 
<img width="516" alt="captura de pantalla 2018-05-30 a la s 12 20 26" src="https://user-images.githubusercontent.com/36163179/40733768-7d43836e-6404-11e8-8bec-29cc58c00f37.png">

And then you see your development then you will find a difference
<img width="213" alt="captura de pantalla 2018-05-30 a la s 12 21 15" src="https://user-images.githubusercontent.com/36163179/40733580-fcd130e6-6403-11e8-83d4-c9f4039635c9.png">

`The main difference is that the technology title like 'Front-End Tools' in the card is 'above' the triangle img and in your development is next to it.`

The main idea of this card is to use pseudoelements... ` investigate and use the '&::before' ` in order to handle that behaviour

2018-05-30 16:45 UTC, HarryPerez commented on index.html
> +        <img width="50px" height="50px" src="./assets/triangle.svg" alt="triangle">
Always put styles in one `styles.scss`file. 
For example in this case i would create an image-container style with `width= ... and height= ...`

2018-05-30 16:45 UTC, HarryPerez commented on index.html
> +
Remove this unnecessary empty line

2018-05-30 16:45 UTC, HarryPerez commented on index.html
> +
Remove this unnecessary empty line

2018-05-30 16:45 UTC, HarryPerez commented on index.html
> +        <p>Front-End Tools</p>
This is an important title, so remember to emphasize it by using tags like `h1`, `h2`.. etc

2018-05-30 16:45 UTC, HarryPerez commented on index.html
> +        <p>Back-End Tools</p>
This is an important title, so remember to emphasize it by using tags like `h1`, `h2`.. etc

2018-05-30 16:45 UTC, HarryPerez commented on scss/titles.scss
> +.title-container{
selectors must be followed by one space -> `.title-container {`

2018-05-30 16:45 UTC, HarryPerez commented on scss/titles.scss
> +    margin: 0 10%;
avoid using % ... `use px or vh instead`.
% is based in the element parents size so if the parent size is defined then all children will not vary.
In this case i would use something like `margin-bottom: 100px`.

2018-05-30 16:45 UTC, HarryPerez commented on index.html
>  <body>
I would add to the body a style like `body-container`in order to establish a `padding` separating the beginning of the page from the content.

2018-05-30 21:20 UTC, HarryPerez requested changes

2018-05-30 21:20 UTC, HarryPerez commented on index.html
> +    <div class="body-container">
Indentation should be 2 spaces (1 tabulation)
For example:
.You have:
<img width="643" alt="captura de pantalla 2018-05-30 a la s 17 08 18" src="https://user-images.githubusercontent.com/36163179/40747766-47d6f6fc-642c-11e8-8b97-92f097c283f5.png">

.It should look like this:
<img width="581" alt="captura de pantalla 2018-05-30 a la s 17 09 08" src="https://user-images.githubusercontent.com/36163179/40747769-4b3cbda4-642c-11e8-9bea-891620bc1dba.png">


`Indentation should be of 2 spaces each`

2018-05-30 21:20 UTC, HarryPerez commented on scss/titles.scss
> +    h2 {
Create style in classes for each tag. It is the best way to reuse them along all your html.
For example if you want to reuse this style in another side that is not nested in `.title-container` you will not be able to use it.
`So i will recommend to create another separated style like 'tech-title' or 'main-title'`

2018-05-30 21:37 UTC, HarryPerez commented on scss/titles.scss
> +        @include image-size(50px);
Good! this is excellent! in the future you will see that this can be used to auto generate margins, paddings..etc

2018-05-30 21:55 UTC, HarryPerez requested changes

2018-05-30 21:55 UTC, HarryPerez commented on scss/titles.scss
> +    &::before{
Use something like these:
<img width="542" alt="captura de pantalla 2018-05-30 a la s 17 54 23" src="https://user-images.githubusercontent.com/36163179/40749587-825f6b50-6432-11e8-80d0-375d3859d2f5.png">

`I will let you to investigate top and left values`

2018-05-30 21:59 UTC, HarryPerez commented on scss/titles.scss
> +    &::before{
The final answer should look something like this 
`<h1 class="xxx-title">Front-End Tools</h1>`
`<h1 class="xxx-title">Back-End Tools</h1>`

2018-05-30 22:59 UTC, HarryPerez requested changes

2018-05-30 22:59 UTC, HarryPerez commented on scss/styles.scss
> +    margin: 0 auto;
`Same about identation`

2018-05-30 22:59 UTC, HarryPerez commented on scss/styles.scss
> +@mixin image-size($size){
`check indentation`

2018-05-30 22:59 UTC, HarryPerez commented on scss/titles.scss
> +    &::before{
Remember that `position: absolute;` is 'relative' to the parent with `position: relative;`. That is why `position: absolute;` is used

2018-05-31 15:09 UTC, HarryPerez requested changes
Very good! you are almost there!

2018-05-31 15:09 UTC, HarryPerez commented on scss/styles.scss
>  * {
check indentation in this whole file. 
Remember that indentation should be `2 spaces or 1 tab`

2018-05-31 15:09 UTC, HarryPerez commented on scss/titles.scss
> +.main-title {
check indentation in this whole file. 
Remember that indentation should be `2 spaces or 1 tab`

2018-05-31 15:26 UTC, HarryPerez requested changes

2018-05-31 15:26 UTC, HarryPerez commented on scss/styles.scss
> +  padding: 0 40px;
Just change this to `padding: 100px` in order to center better the content and we are done.

2018-05-31 15:28 UTC, HarryPerez approved these changes

2018-05-31 15:29 UTC, HarryPerez commented
Very good! You did a great job here! 🥇

2018-05-31 15:34 UTC, SKOLZ approved these changes

2018-05-31 15:35 UTC, merged